# Generated by Django 3.0.7 on 2020-11-11 03:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150, unique=True)),
                ('postcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('status', models.CharField(max_length=10)),
                ('institution', models.CharField(max_length=10)),
                ('jenis', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('service', models.CharField(max_length=250)),
                ('panel', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='clinic_image/')),
                ('hour', models.TimeField()),
            ],
        ),
    ]
